name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build \
            --build-arg VITE_BASE_URL="${{ secrets.VITE_BASE_URL }}" \
            -t fathimathusuhaila123/tiffinmate-prod .
      - name: Publish image to docker hub
        run: docker push fathimathusuhaila123/tiffinmate-prod:latest   

  deploy: 
    needs: build
    runs-on: aws-ec2    
    steps:
      - name: Pull image from docker hub
        run: docker pull fathimathusuhaila123/tiffinmate-prod:latest 
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 \
            -e VITE_BASE_URL="${{ secrets.VITE_BASE_URL }}" \
            --name reactContainer fathimathusuhaila123/tiffinmate-prod 